### ISSUE TITLE
为什么/pokemon/list接口不能传page和size呢，怎么传都是全部返回数据

### ISSUE THREAD

**Issue by rogepi** [fantasticmao/pokemon-wiki#27]
如题

**Comment by fantasticmao** [comment]
你好，虽然我在 controller 层的确是定义了这两个参数，但目前是没有实现的。。

https://github.com/fantasticmao/pokemon-wiki/blob/6830caf1e7b86b44d6913562cd287a56195d5f81/pokemon-wiki-web/src/main/java/cn/fantasticmao/pokemon/web/controller/PokemonController.java#L46-L61

https://github.com/fantasticmao/pokemon-wiki/blob/6830caf1e7b86b44d6913562cd287a56195d5f81/pokemon-wiki-web/src/main/java/cn/fantasticmao/pokemon/web/service/impl/PokemonServiceImpl.java#L122-L131

所以在 api doc 里也没有提及这两个参数。。

https://github.com/fantasticmao/pokemon-wiki/blob/6830caf1e7b86b44d6913562cd287a56195d5f81/apiDoc/%E5%AE%9D%E5%8F%AF%E6%A2%A6%E7%9B%B8%E5%85%B3%E6%8E%A5%E5%8F%A3.md?plain=1#L3-L21

最近在支持第九世代 的图鉴，等这周末我支持一下吧 :)

**Comment by fantasticmao** [comment]
宝可梦列表接口已经支持 `page` 和 `size` 这两个分页参数了。

```shell
curl -i \
-H 'Accept: application/json' \
'https://pokemon.fantasticmao.cn/pokemon/list?generation=3&eggGroup=%E4%BA%BA%E5%9E%8B&page=0&size=10'
```
