### ISSUE TITLE
Could API provide nameEn search?

### ISSUE THREAD

**Issue by louis70109** [fantasticmao/pokemon-wiki#30]
As [ApiDoc](https://github.com/fantasticmao/pokemon-wiki/blob/master/apiDoc/%E6%8B%9B%E5%BC%8F%E7%9B%B8%E5%85%B3%E6%8E%A5%E5%8F%A3.md#%E6%8B%9B%E5%BC%8F%E8%AF%A6%E6%83%85%E6%8E%A5%E5%8F%A3), it can search by ZH query string. (Very helpful for me!)
But sometimes we are wanting to query by EN.
Could API can provide EN query? Thanks!

**Comment by fantasticmao** [comment]
@louis70109 Hi louis70109, sorry for reply late, and of course, I will support this feature this weekend.

**Comment by fantasticmao** [comment]
@louis70109 Hi, it is now supported to use the `nameEn` field to query Pokemons, Moves, Abilities and Items. You can have a try with following curls, and [apiDoc](https://github.com/fantasticmao/pokemon-wiki/tree/master/apiDoc) has also been updated:

```
curl -i 'https://pokemon.fantasticmao.cn/pokemon/detail?nameZh=%E5%A6%99%E8%9B%99&nameEn=Bulba'
```

```
curl -i 'https://pokemon.fantasticmao.cn/move/detail?nameZh=%E7%81%AB&nameEn=Fire'
```

```
curl -i 'https://pokemon.fantasticmao.cn/ability/detail?nameZh=%E7%81%AB&nameEn=Fire'
```

```
curl -i 'https://pokemon.fantasticmao.cn/item/detail?nameZh=%E7%81%AB&nameEn=Fire'
```

**Comment by louis70109** [comment]
@fantasticmao Thank you so much! It is very helpful.
